set(SRC_FILES
	Cursor.cpp
	draw_test.cpp
	InitScreen.cpp
	InitScreenBackground.cpp
	main.cpp
	Programs.cpp
	TheApp.cpp
	Draw/Atlas_Region.cpp
	Draw/Draw_2D.cpp
	Draw/Fonts.cpp
	Draw/Image_Region.cpp
	Draw/NumberDrawer.cpp
	Draw/ReText.cpp
	Draw/ReTexture.cpp
	Draw/Text_box.cpp
	Draw/Text_layout.cpp
	Draw/Text_layout_all.cpp
	Draw/Text_layout_color.cpp
	Draw/Text_layout_normal.cpp
	Game_object/action/Actions.cpp
	Game_object/action/Action_group_handler.cpp
	Game_object/action/Anim_set_action.cpp
	Game_object/action/Apply_power_action.cpp
	Game_object/action/Card_use_end_action.cpp 
	Game_object/action/Card_use_start_action.cpp
	Game_object/action/Damage_action.cpp
	Game_object/action/Draw_card_action.cpp
	Game_object/action/Effect_gen_capsule_action.cpp
	Game_object/action/Empty_shuffle_action.cpp
	Game_object/action/Gain_block_action.cpp
	Game_object/action/Random_monster_gain_block.cpp
	Game_object/action/Reduce_power_action.cpp
	Game_object/action/Remove_power_action.cpp
	Game_object/button/Cancel_button.cpp
	Game_object/button/Confirm_button.cpp
	Game_object/button/End_turn_button.cpp
	Game_object/button/Menu_button.cpp
	Game_object/button/Proceed_button.cpp
	Game_object/button/Return_to_start_button.cpp
	Game_object/button/Skip_button.cpp
	Game_object/card/Cards.cpp
	Game_object/card/Card_generate.cpp
	Game_object/card/Card_group.cpp
	Game_object/card/Card_group_handler.cpp
	Game_object/card/Card_soul.cpp
	Game_object/card/red/Anger.cpp
	Game_object/card/red/Barricade.cpp
	Game_object/card/red/Clash.cpp
	Game_object/card/red/Clothesline.cpp
	Game_object/card/red/Defend.cpp
	Game_object/card/red/Shockwave.cpp
	Game_object/card/red/Strike_red.cpp
	Game_object/character/Characters.cpp
	Game_object/character/Monster_group.cpp
	Game_object/character/Monster_group_creater.cpp
	Game_object/character/Player.cpp
	Game_object/character/Monster/AcidSlimeL.cpp
	Game_object/character/Monster/AcidSlimeM.cpp
	Game_object/character/Monster/AcidSlimeS.cpp
	Game_object/character/Monster/BlueSlaver.cpp
	Game_object/character/Monster/Cultist.cpp
	Game_object/character/Monster/FatGremlin.cpp
	Game_object/character/Monster/FungiBeast.cpp
	Game_object/character/Monster/GreenLouse.cpp
	Game_object/character/Monster/GremlinNob.cpp
	Game_object/character/Monster/JawWorm.cpp
	Game_object/character/Monster/Lagavulin.cpp
	Game_object/character/Monster/Looter.cpp
	Game_object/character/Monster/MadGremlin.cpp
	Game_object/character/Monster/Monsters.cpp
	Game_object/character/Monster/RedLouse.cpp
	Game_object/character/Monster/RedSlaver.cpp
	Game_object/character/Monster/Sentry.cpp
	Game_object/character/Monster/ShieldGremlin.cpp
	Game_object/character/Monster/SlimeBoss.cpp
	Game_object/character/Monster/SneakyGremlin.cpp
	Game_object/character/Monster/SpikeSlimeL.cpp
	Game_object/character/Monster/SpikeSlimeM.cpp
	Game_object/character/Monster/SpikeSlimeS.cpp
	Game_object/character/Monster/TheGuardian.cpp
	Game_object/character/Monster/WizardGremlin.cpp
	Game_object/dungeon/Combat_reward_screen.cpp
	Game_object/dungeon/Death_screen.cpp
	Game_object/dungeon/Dungeons.cpp
	Game_object/dungeon/Dungeon_manager.cpp
	Game_object/dungeon/Dungeon_screen.cpp
	Game_object/dungeon/Grid_card_screen.cpp
	Game_object/dungeon/Overlay.cpp
	Game_object/dungeon/Shop_screen.cpp
	Game_object/dungeon/Victory_screen.cpp
	Game_object/dungeon/Grid_screen_action/Grid_screen_action.cpp
	Game_object/dungeon/Grid_screen_action/Grid_screen_purge_action.cpp
	Game_object/dungeon/Grid_screen_action/Grid_screen_upgrade_action.cpp
	Game_object/dungeon/Grid_screen_action/Render_arrow.cpp
	Game_object/effect/Auto_release_pool_manager.cpp
	Game_object/effect/Battle_start_eff.cpp
	Game_object/effect/block_broken_eff.cpp
	Game_object/effect/Border_flash_eff.cpp
	Game_object/effect/Buff_particle_eff.cpp
	Game_object/effect/Camfire_bubble_effect.cpp
	Game_object/effect/Camfire_burning_effect.cpp
	Game_object/effect/Card_flash.cpp
	Game_object/effect/Card_glow_border.cpp
	Game_object/effect/Card_proof_particle.cpp
	Game_object/effect/Card_trail_effect.cpp
	Game_object/effect/Damage_impact_curvy_eff.cpp
	Game_object/effect/Debuff_particle_eff.cpp
	Game_object/effect/Effects.cpp
	Game_object/effect/Effect_group.cpp
	Game_object/effect/End_turn_button_glow.cpp
	Game_object/effect/Enemy_turn_eff.cpp
	Game_object/effect/Exhaust_blur_eff.cpp
	Game_object/effect/Exhaust_ember_eff.cpp
	Game_object/effect/Fade_wide.cpp
	Game_object/effect/Flash_attack_effect.cpp
	Game_object/effect/Flying_spike_eff.cpp
	Game_object/effect/Hammer_effect.cpp
	Game_object/effect/Map_circle_effect.cpp
	Game_object/effect/Player_turn_eff.cpp
	Game_object/effect/Power_buff_debuff_eff.cpp
	Game_object/effect/Power_remove_text_eff.cpp
	Game_object/effect/Purge_card_eff.cpp
	Game_object/effect/Refresh_energy_effect.cpp
	Game_object/effect/Rest_option_black_screen.cpp
	Game_object/effect/Shield_particle_eff.cpp
	Game_object/effect/Shine_particle.cpp
	Game_object/effect/Slash_eff.cpp
	Game_object/effect/Sleep_cover_eff.cpp
	Game_object/effect/Stun_star_eff.cpp
	Game_object/effect/Unknown_particle_eff.cpp
	Game_object/effect/Vertical_aura.cpp
	Game_object/effect/Weighty_impact_eff.cpp
	Game_object/effect_gen/Card_upgrade_eff_gen.cpp
	Game_object/effect_gen/Effect_gen_group.cpp
	Game_object/effect_gen/Exhaust_card_eff_gen.cpp
	Game_object/effect_gen/Purge_card_eff_gen.cpp
	Game_object/effect_gen/Show_card_briefly.cpp
	Game_object/effect_gen/Show_card_to_discard.cpp
	Game_object/energy_orb/Red_orb.cpp
	Game_object/map/Dungeon_map.cpp
	Game_object/map/Legend.cpp
	Game_object/map/Legend_item.cpp
	Game_object/map/Map_dot.cpp
	Game_object/map/Map_edge.cpp
	Game_object/map/Map_generator.cpp
	Game_object/map/Map_node.cpp
	Game_object/panel/Energy_panel.cpp
	Game_object/panel/Panels.cpp
	Game_object/power/Powers.cpp
	Game_object/power/Power_creator.cpp
	Game_object/power/Power_group.cpp
	Game_object/power/Weak_power.cpp
	Game_object/reward_item/Card_reward.cpp
	Game_object/reward_item/Card_reward_item.cpp
	Game_object/reward_item/Gold_reward_item.cpp
	Game_object/reward_item/Reward_item.cpp
	Game_object/room/Elite_room.cpp
	Game_object/room/Monster_room.cpp
	Game_object/room/Rest_room.cpp
	Game_object/room/Shop_merchant.cpp
	Game_object/room/Shop_room.cpp
	Game_object/room/Treasure_item.cpp
	Game_object/room/Treasure_room.cpp
	Game_object/room/rest_room_options/Options.cpp
	Game_object/room/rest_room_options/Option_handler.cpp
	Game_object/room/rest_room_options/Rest_option.cpp
	Game_object/room/rest_room_options/Smith_option.cpp
	Game_object/room/Treasure_type/Large_chest.cpp
	Game_object/room/Treasure_type/Medium_chest.cpp
	Game_object/room/Treasure_type/Small_chest.cpp
	Game_object/scene/Bottom_scene.cpp
	Game_object/scene/Scenes.cpp
	RUtil/All_Image.cpp
	RUtil/Atlas_Reader.cpp
	RUtil/Cards_Text_Reader.cpp
	RUtil/Game_Input.cpp
	RUtil/Hitbox.cpp
	RUtil/Image_book.cpp
	RUtil/Powers_Text_Reader.cpp
	RUtil/Random.cpp
	RUtil/Scroll.cpp
	RUtil/Some_Math.cpp
	RUtil/Text_layout_creator.cpp
	RUtil/Text_Vector_Reader.cpp
	top_panel/Deck_icon.cpp
	top_panel/Floor_icon.cpp
	top_panel/Gold_bag_icon.cpp
	top_panel/Heart_icon.cpp
	top_panel/Map_icon.cpp
	top_panel/Setting_icon.cpp
	top_panel/Top_panel.cpp
)

set(INCLUDE_FILES
	Cursor.hpp
	draw_test.hpp
	InitScreen.hpp
	InitScreenBackground.hpp
	Programs.hpp
	TheApp.hpp
	WindowSize.hpp
	Draw/Atlas_Region.hpp
	Draw/Draw_2D.hpp
	Draw/Fonts.hpp
	Draw/Image_Region.hpp
	Draw/NumberDrawer.hpp
	Draw/ReText.hpp
	Draw/ReTexture.hpp
	Draw/Text_box.hpp
	Draw/Text_layout.hpp
	Draw/Text_layout_all.hpp
	Draw/Text_layout_color.hpp
	Draw/Text_layout_normal.hpp
	Game_object/Card_pos_setter.hpp
	Game_object/Damage_info.hpp
	Game_object/Group_template.hpp
	Game_object/abstraction/CardPrototype.hpp
	Game_object/abstraction/Is_screen.hpp
	Game_object/abstraction/Monster_move_tracker.hpp
	Game_object/abstraction/Reusable.hpp
	Game_object/action/Actions.hpp
	Game_object/action/Action_group.hpp
	Game_object/action/Action_group_handler.hpp
	Game_object/action/Anim_set_action.hpp
	Game_object/action/Apply_power_action.hpp
	Game_object/action/Card_use_end_action.hpp
	Game_object/action/Card_use_start_action.hpp
	Game_object/action/Damage_action.hpp
	Game_object/action/Death_lock_action.hpp
	Game_object/action/Discard_all_action.hpp
	Game_object/action/Draw_card_action.hpp
	Game_object/action/Effect_capsule_action.hpp
	Game_object/action/Effect_gen_capsule_action.hpp
	Game_object/action/Empty_shuffle_action.hpp
	Game_object/action/Enable_end_button_action.hpp
	Game_object/action/Gain_block_action.hpp
	Game_object/action/Gain_energy_action.hpp
	Game_object/action/Random_monster_gain_block.hpp
	Game_object/action/Reduce_power_action.hpp
	Game_object/action/Remove_power_action.hpp
	Game_object/action/Show_card_to_discard_action.hpp
	Game_object/action/Spawn_monster_action.hpp
	Game_object/action/Suicide_action.hpp
	Game_object/action/Wait_action.hpp
	Game_object/button/Cancel_button.hpp
	Game_object/button/Confirm_button.hpp
	Game_object/button/End_turn_button.hpp
	Game_object/button/Menu_button.hpp
	Game_object/button/Proceed_button.hpp
	Game_object/button/Return_to_start_button.hpp
	Game_object/button/Skip_button.hpp
	Game_object/card/Cards.hpp
	Game_object/card/Card_generate.hpp
	Game_object/card/Card_group.hpp
	Game_object/card/Card_group_handler.hpp
	Game_object/card/Card_item.hpp
	Game_object/card/Card_soul.hpp
	Game_object/card/red/Anger.hpp
	Game_object/card/red/Barricade.hpp
	Game_object/card/red/Clash.hpp
	Game_object/card/red/Clothesline.hpp
	Game_object/card/red/Defend.hpp
	Game_object/card/red/Shockwave.hpp
	Game_object/card/red/Strike_red.hpp
	Game_object/card/status/Slimed.hpp
	Game_object/character/AllMonster.hpp
	Game_object/character/Characters.hpp
	Game_object/character/Monster_group.hpp
	Game_object/character/Monster_group_creater.hpp
	Game_object/character/Player.hpp
	Game_object/character/Monster/AcidSlimeL.hpp
	Game_object/character/Monster/AcidSlimeM.hpp
	Game_object/character/Monster/AcidSlimeS.hpp
	Game_object/character/Monster/BlueSlaver.hpp
	Game_object/character/Monster/Cultist.hpp
	Game_object/character/Monster/FatGremlin.hpp
	Game_object/character/Monster/FungiBeast.hpp
	Game_object/character/Monster/GreenLouse.hpp
	Game_object/character/Monster/GremlinNob.hpp
	Game_object/character/Monster/JawWorm.hpp
	Game_object/character/Monster/Lagavulin.hpp
	Game_object/character/Monster/Looter.hpp
	Game_object/character/Monster/MadGremlin.hpp
	Game_object/character/Monster/Monsters.hpp
	Game_object/character/Monster/RedLouse.hpp
	Game_object/character/Monster/RedSlaver.hpp
	Game_object/character/Monster/Sentry.hpp
	Game_object/character/Monster/ShieldGremlin.hpp
	Game_object/character/Monster/SlimeBoss.hpp
	Game_object/character/Monster/SneakyGremlin.hpp
	Game_object/character/Monster/SpikeSlimeL.hpp
	Game_object/character/Monster/SpikeSlimeM.hpp
	Game_object/character/Monster/SpikeSlimeS.hpp
	Game_object/character/Monster/TheGuardian.hpp
	Game_object/character/Monster/WizardGremlin.hpp
	Game_object/dungeon/Combat_reward_screen.hpp
	Game_object/dungeon/Death_screen.hpp
	Game_object/dungeon/Dungeons.hpp
	Game_object/dungeon/Dungeon_manager.hpp
	Game_object/dungeon/Dungeon_screen.hpp
	Game_object/dungeon/Dungeon_shared.hpp
	Game_object/dungeon/Grid_card_screen.hpp
	Game_object/dungeon/Overlay.hpp
	Game_object/dungeon/Shop_screen.hpp
	Game_object/dungeon/Victory_screen.hpp
	Game_object/dungeon/Grid_screen_action/Grid_screen_action.hpp
	Game_object/dungeon/Grid_screen_action/Grid_screen_purge_action.hpp
	Game_object/dungeon/Grid_screen_action/Grid_screen_upgrade_action.hpp
	Game_object/dungeon/Grid_screen_action/Render_arrow.hpp
	Game_object/effect/Auto_release_pool_manager.hpp
	Game_object/effect/Battle_start_eff.hpp
	Game_object/effect/block_broken_eff.hpp
	Game_object/effect/Border_flash_eff.hpp
	Game_object/effect/Buff_particle_eff.hpp
	Game_object/effect/Camfire_bubble_effect.hpp
	Game_object/effect/Camfire_burning_effect.hpp
	Game_object/effect/Card_flash.hpp
	Game_object/effect/Card_glow_border.hpp
	Game_object/effect/Card_proof_particle.hpp
	Game_object/effect/Card_trail_effect.hpp
	Game_object/effect/Damage_impact_curvy_eff.hpp
	Game_object/effect/Debuff_particle_eff.hpp
	Game_object/effect/Effects.hpp
	Game_object/effect/Effect_group.hpp
	Game_object/effect/Effect_pool.hpp
	Game_object/effect/Effect_pool.inl
	Game_object/effect/Empower_circle_eff.hpp
	Game_object/effect/End_turn_button_glow.hpp
	Game_object/effect/Enemy_turn_eff.hpp
	Game_object/effect/Exhaust_blur_eff.hpp
	Game_object/effect/Exhaust_ember_eff.hpp
	Game_object/effect/Fade_wide.hpp
	Game_object/effect/Flash_attack_effect.hpp
	Game_object/effect/Flash_intent_particle_eff.hpp
	Game_object/effect/Flash_power_eff.hpp
	Game_object/effect/Flying_spike_eff.hpp
	Game_object/effect/Hammer_effect.hpp
	Game_object/effect/Map_circle_effect.hpp
	Game_object/effect/Player_turn_eff.hpp
	Game_object/effect/Power_buff_debuff_eff.hpp
	Game_object/effect/Power_remove_text_eff.hpp
	Game_object/effect/Purge_card_eff.hpp
	Game_object/effect/Refresh_energy_effect.hpp
	Game_object/effect/Rest_option_black_screen.hpp
	Game_object/effect/Shield_particle_eff.hpp
	Game_object/effect/Shine_particle.hpp
	Game_object/effect/Slash_eff.hpp
	Game_object/effect/Sleep_cover_eff.hpp
	Game_object/effect/Stun_star_eff.hpp
	Game_object/effect/Unknown_particle_eff.hpp
	Game_object/effect/Vertical_aura.hpp
	Game_object/effect/Weighty_impact_eff.hpp
	Game_object/effect_gen/Card_paticle_gen.hpp
	Game_object/effect_gen/Card_upgrade_eff_gen.hpp
	Game_object/effect_gen/Clash_eff_gen.hpp
	Game_object/effect_gen/Effect_gen.hpp
	Game_object/effect_gen/Effect_gen_group.hpp
	Game_object/effect_gen/Empower_circle_gen.hpp
	Game_object/effect_gen/Exhaust_card_eff_gen.hpp
	Game_object/effect_gen/Flash_intent_particle_gen.hpp
	Game_object/effect_gen/Power_buff_debuff_gen.hpp
	Game_object/effect_gen/Power_remove_text_gen.hpp
	Game_object/effect_gen/Purge_card_eff_gen.hpp
	Game_object/effect_gen/Show_card_briefly.hpp
	Game_object/effect_gen/Show_card_to_discard.hpp
	Game_object/effect_gen/Vertical_aura_gen.hpp
	Game_object/effect_gen/Weighty_impact_gen.hpp
	Game_object/energy_orb/Energy_orb.hpp
	Game_object/energy_orb/Red_orb.hpp
	Game_object/map/Dungeon_map.hpp
	Game_object/map/Legend.hpp
	Game_object/map/Legend_item.hpp
	Game_object/map/Map_dot.hpp
	Game_object/map/Map_edge.hpp
	Game_object/map/Map_generator.hpp
	Game_object/map/Map_node.hpp
	Game_object/panel/Energy_panel.hpp
	Game_object/panel/Panels.hpp
	Game_object/power/Barricade_power.hpp
	Game_object/power/Frail_power.hpp
	Game_object/power/Powers.hpp
	Game_object/power/Power_creator.hpp
	Game_object/power/Power_group.hpp
	Game_object/power/Ritual_power.hpp
	Game_object/power/Strength_power.hpp
	Game_object/power/Vulnerable_power.hpp
	Game_object/power/Weak_power.hpp
	Game_object/reward_item/Card_reward.hpp
	Game_object/reward_item/Card_reward_item.hpp
	Game_object/reward_item/Gold_reward_item.hpp
	Game_object/reward_item/Reward_item.hpp
	Game_object/room/Elite_room.hpp
	Game_object/room/Monster_room.hpp
	Game_object/room/Rest_room.hpp
	Game_object/room/Rooms.hpp
	Game_object/room/Shop_item.hpp
	Game_object/room/Shop_merchant.hpp
	Game_object/room/Shop_room.hpp
	Game_object/room/Treasure_item.hpp
	Game_object/room/Treasure_room.hpp
	Game_object/room/rest_room_options/Options.hpp
	Game_object/room/rest_room_options/Option_handler.hpp
	Game_object/room/rest_room_options/Rest_option.hpp
	Game_object/room/rest_room_options/Smith_option.hpp
	Game_object/room/Treasure_type/Large_chest.hpp
	Game_object/room/Treasure_type/Medium_chest.hpp
	Game_object/room/Treasure_type/Small_chest.hpp
	Game_object/scene/Bottom_scene.hpp
	Game_object/scene/Scenes.hpp
	Game_object/top_panel/Basic_panel.hpp
	Game_object/top_panel/Deck_icon.hpp
	Game_object/top_panel/Floor_icon.hpp
	Game_object/top_panel/Gold_bag_icon.hpp
	Game_object/top_panel/Heart_icon.hpp
	Game_object/top_panel/Map_icon.hpp
	Game_object/top_panel/Setting_icon.hpp
	Game_object/top_panel/Top_panel.hpp
	RUtil/All_Image.hpp
	RUtil/Atlas_Reader.hpp
	RUtil/Cards_Text_Reader.hpp
	RUtil/ColorValuesOnly.hpp
	RUtil/File_Pos_Getter.hpp
	RUtil/Game_Input.hpp
	RUtil/Hitbox.hpp
	RUtil/Image_book.hpp
	RUtil/Powers_Text_Reader.hpp
	RUtil/Probability_selector.hpp
	RUtil/Random.hpp
	RUtil/Random_package.hpp
	RUtil/Scroll.hpp
	RUtil/Some_Math.hpp
	RUtil/Text_layout_creator.hpp
	RUtil/Text_Vector_Reader.hpp
	RUtil/Weighted_index_picker.hpp
)

set(TEST_FILES
)