set(SRC_FILES
	Cursor.cpp
	draw_test.cpp
	InitScreen.cpp
	main.cpp
	Programs.cpp
	TheApp.cpp
	Draw/Atlas_Region.cpp
	Draw/Draw_2D.cpp
	Draw/Fonts.cpp
	Draw/Image_Region.cpp
	Draw/NumberDrawer.cpp
	Draw/ReText.cpp
	Draw/ReTexture.cpp
	Draw/Text_box.cpp
	Draw/Text_layout.cpp
	Draw/Text_layout_all.cpp
	Draw/Text_layout_color.cpp
	Draw/Text_layout_normal.cpp
	Game_object/action/Actions.cpp
	Game_object/action/Action_group_handler.cpp
	Game_object/action/Card_use_action.cpp
	Game_object/action/Damage_action.cpp
	Game_object/action/Draw_card_action.cpp
	Game_object/action/Empty_shuffle_action.cpp
	Game_object/button/End_turn_button.cpp
	Game_object/card/Cards.cpp
	Game_object/card/Card_group.cpp
	Game_object/card/Card_group_handler.cpp
	Game_object/card/Card_soul.cpp
	Game_object/card/red/Anger.cpp
	Game_object/card/red/Strike_red.cpp
	Game_object/character/Characters.cpp
	Game_object/character/Monster_group.cpp
	Game_object/character/Monster_group_creater.cpp
	Game_object/character/Player.cpp
	Game_object/character/Monster/AcidSlimeL.cpp
	Game_object/character/Monster/AcidSlimeM.cpp
	Game_object/character/Monster/AcidSlimeS.cpp
	Game_object/character/Monster/Cultist.cpp
	Game_object/character/Monster/FatGremlin.cpp
	Game_object/character/Monster/GreenLouse.cpp
	Game_object/character/Monster/JawWorm.cpp
	Game_object/character/Monster/Monsters.cpp
	Game_object/character/Monster/RedLouse.cpp
	Game_object/character/Monster/SpikeSlimeL.cpp
	Game_object/character/Monster/SpikeSlimeM.cpp
	Game_object/character/Monster/SpikeSlimeS.cpp
	Game_object/character/Monster/TempMonster.cpp
	Game_object/dungeon/Dungeons.cpp
	Game_object/dungeon/Dungeon_manager.cpp
	Game_object/dungeon/Dungeon_screen.cpp
	Game_object/dungeon/Overlay.cpp
	Game_object/effect/Auto_release_pool_manager.cpp
	Game_object/effect/Card_flash.cpp
	Game_object/effect/Card_glow_border.cpp
	Game_object/effect/Card_proof_particle.cpp
	Game_object/effect/Card_trail_effect.cpp
	Game_object/effect/Effects.cpp
	Game_object/effect/Effect_group.cpp
	Game_object/effect/End_turn_button_glow.cpp
	Game_object/effect/Fade_wide.cpp
	Game_object/effect/Flash_attack_effect.cpp
	Game_object/effect/Map_circle_effect.cpp
	Game_object/effect/Refresh_energy_effect.cpp
	Game_object/effect_gen/Effect_gen_group.cpp
	Game_object/effect_gen/Show_card_to_discard.cpp
	Game_object/energy_orb/Red_orb.cpp
	Game_object/map/Dungeon_map.cpp
	Game_object/map/Legend.cpp
	Game_object/map/Legend_item.cpp
	Game_object/map/Map_dot.cpp
	Game_object/map/Map_edge.cpp
	Game_object/map/Map_generator.cpp
	Game_object/map/Map_node.cpp
	Game_object/panel/Energy_panel.cpp
	Game_object/panel/Panels.cpp
	Game_object/room/Monster_room.cpp
	Game_object/scene/Bottom_scene.cpp
	Game_object/scene/Scenes.cpp
	RUtil/All_Image.cpp
	RUtil/Atlas_Reader.cpp
	RUtil/Game_Input.cpp
	RUtil/Hitbox.cpp
	RUtil/Image_book.cpp
	RUtil/Random.cpp
	RUtil/Some_Math.cpp
	RUtil/Text_Vector_Reader.cpp
)

set(INCLUDE_FILES
	AppStatus.hpp
	Cursor.hpp
	draw_test.hpp
	InitScreen.hpp
	Programs.hpp
	TheApp.hpp
	WindowSize.hpp
	Draw/Atlas_Region.hpp
	Draw/Draw_2D.hpp
	Draw/Fonts.hpp
	Draw/Image_Region.hpp
	Draw/NumberDrawer.hpp
	Draw/ReText.hpp
	Draw/ReTexture.hpp
	Draw/Text_box.hpp
	Draw/Text_layout.hpp
	Draw/Text_layout_all.hpp
	Draw/Text_layout_color.hpp
	Draw/Text_layout_normal.hpp
	Game_object/Damage_info.hpp
	Game_object/Group_template.hpp
	Game_object/action/Actions.hpp
	Game_object/action/Action_group.hpp
	Game_object/action/Action_group_handler.hpp
	Game_object/action/Card_use_action.hpp
	Game_object/action/Damage_action.hpp
	Game_object/action/Discard_all_action.hpp
	Game_object/action/Draw_card_action.hpp
	Game_object/action/Empty_shuffle_action.hpp
	Game_object/action/Enable_end_button_action.hpp
	Game_object/action/Wait_action.hpp
	Game_object/button/End_turn_button.hpp
	Game_object/card/Cards.hpp
	Game_object/card/Card_group.hpp
	Game_object/card/Card_group_handler.hpp
	Game_object/card/Card_item.hpp
	Game_object/card/Card_soul.hpp
	Game_object/card/red/Anger.hpp
	Game_object/card/red/Strike_red.hpp
	Game_object/character/AllMonster.hpp
	Game_object/character/Characters.hpp
	Game_object/character/Monster_group.hpp
	Game_object/character/Monster_group_creater.hpp
	Game_object/character/Player.hpp
	Game_object/character/Monster/AcidSlimeL.hpp
	Game_object/character/Monster/AcidSlimeM.hpp
	Game_object/character/Monster/AcidSlimeS.hpp
	Game_object/character/Monster/Cultist.hpp
	Game_object/character/Monster/FatGremlin.hpp
	Game_object/character/Monster/GreenLouse.hpp
	Game_object/character/Monster/JawWorm.hpp
	Game_object/character/Monster/Monsters.hpp
	Game_object/character/Monster/RedLouse.hpp
	Game_object/character/Monster/SpikeSlimeL.hpp
	Game_object/character/Monster/SpikeSlimeM.hpp
	Game_object/character/Monster/SpikeSlimeS.hpp
	Game_object/character/Monster/TempMonster.hpp
	Game_object/dungeon/Dungeons.hpp
	Game_object/dungeon/Dungeon_manager.hpp
	Game_object/dungeon/Dungeon_screen.hpp
	Game_object/dungeon/Dungeon_shared.hpp
	Game_object/dungeon/Overlay.hpp
	Game_object/effect/Auto_release_pool_manager.hpp
	Game_object/effect/Card_flash.hpp
	Game_object/effect/Card_glow_border.hpp
	Game_object/effect/Card_proof_particle.hpp
	Game_object/effect/Card_trail_effect.hpp
	Game_object/effect/Effects.hpp
	Game_object/effect/Effect_group.hpp
	Game_object/effect/Effect_pool.hpp
	Game_object/effect/Effect_pool.inl
	Game_object/effect/End_turn_button_glow.hpp
	Game_object/effect/Fade_wide.hpp
	Game_object/effect/Flash_attack_effect.hpp
	Game_object/effect/Map_circle_effect.hpp
	Game_object/effect/Refresh_energy_effect.hpp
	Game_object/effect_gen/Card_paticle_gen.hpp
	Game_object/effect_gen/Effect_gen.hpp
	Game_object/effect_gen/Effect_gen_group.hpp
	Game_object/effect_gen/Show_card_to_discard.hpp
	Game_object/energy_orb/Energy_orb.hpp
	Game_object/energy_orb/Red_orb.hpp
	Game_object/interface/CardPrototype.hpp
	Game_object/interface/Is_screen.hpp
	Game_object/interface/Reusable.hpp
	Game_object/map/Dungeon_map.hpp
	Game_object/map/Legend.hpp
	Game_object/map/Legend_item.hpp
	Game_object/map/Map_dot.hpp
	Game_object/map/Map_edge.hpp
	Game_object/map/Map_generator.hpp
	Game_object/map/Map_node.hpp
	Game_object/panel/Energy_panel.hpp
	Game_object/panel/Panels.hpp
	Game_object/room/Monster_room.hpp
	Game_object/room/Rooms.hpp
	Game_object/scene/Bottom_scene.hpp
	Game_object/scene/Scenes.hpp
	RUtil/All_Image.hpp
	RUtil/Atlas_Reader.hpp
	RUtil/ColorValuesOnly.hpp
	RUtil/Game_Input.hpp
	RUtil/Hitbox.hpp
	RUtil/Image_book.hpp
	RUtil/Random.hpp
	RUtil/Random_package.hpp
	RUtil/Some_Math.hpp
	RUtil/Text_Vector_Reader.hpp
)

set(TEST_FILES
)